from dataclasses import dataclass
from typing import Any, Final, Sequence

from pydantic import BaseModel, create_model

from falcon_swoop import ApiBaseResource
from falcon_swoop.error import FalconSwoopDocGenerationError
from falcon_swoop.binary import OpAsgiBinary, OpBinary
from falcon_swoop.openapi.pydantic_util import model_json_schema
from falcon_swoop.openapi.spec import (
    JsonSchema,
    OpenApiComponents,
    OpenApiDocument,
    OpenApiExample,
    OpenApiInfo,
    OpenApiMediaType,
    OpenApiOperation,
    OpenApiPathItem,
    OpenApiParameter,
    OpenApiParameterType,
    OpenApiReference,
    OpenApiRequestBody,
    OpenApiResponse,
)
from falcon_swoop.operation import (
    HttpMethod,
    OpFuncParamInput,
    OpInfo,
    OpInfoWithSpec,
    OpResponseDoc,
    OpRequestDoc,
    OpExample,
    OpType,
    OpTypeDoc,
)


@dataclass
class OpenApiGeneratorSettings:
    # when active identical parameters will be put in components.parameters and referenced, leads to more compact spec
    reuse_parameters_if_possible: bool = True
    # when active removes title field autogenerated by pydantic (in object schemas)
    suppress_title_in_object_schemas: bool = True
    # when active removes title field autogenerated by pydantic (in parameter schemas)
    suppress_title_in_param_schemas: bool = True


@dataclass
class OpenApiGeneratorResult:
    spec: OpenApiDocument


class OpenApiParameterCollector:
    REF_TEMPLATE: Final[str] = "#/components/parameters/{param}"

    def __init__(self) -> None:
        self.__counts: dict[OpenApiParameterType, int] = {
            OpenApiParameterType.PATH: 0,
            OpenApiParameterType.QUERY: 0,
            OpenApiParameterType.COOKIE: 0,
            OpenApiParameterType.HEADER: 0,
        }
        self.__params: list[OpenApiParameter] = []
        self.__names: list[str] = []

    def __build_params(
        self, param_type: OpenApiParameterType, param_input: OpFuncParamInput, suppress_title: bool = False
    ) -> list[OpenApiParameter]:
        params = []
        schema = model_json_schema(param_input.model_type, suppress_title=suppress_title)
        for prop_name, prop_schema in schema["properties"].items():
            pi = param_input.param_by_input_name[prop_name]
            param = OpenApiParameter(
                name=prop_name,
                in_=param_type,
                schema_=prop_schema,
                deprecated=pi.info.deprecated or False,
                description=pi.info.description,
                required=not pi.optional,
            )
            params.append(param)
        return params

    def __collect_param(self, param: OpenApiParameter, reuse: bool) -> OpenApiReference:
        if reuse and param in self.__params:
            param_index = self.__params.index(param)
            param_name = self.__names[param_index]

        else:
            param_name = f"{param.in_.value}{self.__counts[param.in_]}"
            self.__counts[param.in_] += 1
            self.__params.append(param)
            self.__names.append(param_name)

        return OpenApiReference(ref=self.REF_TEMPLATE.format(param=param_name))

    def build_params(
        self,
        param_type: OpenApiParameterType,
        param_input: OpFuncParamInput | None,
        reuse: bool,
        collect: bool = True,
        suppress_title: bool = False,
    ) -> list[OpenApiParameter | OpenApiReference]:
        if param_input is None:
            return []

        params_out: list[OpenApiParameter | OpenApiReference] = []
        params = self.__build_params(param_type, param_input, suppress_title=suppress_title)

        if not collect:
            params_out = params  # type: ignore[assignment]
        else:
            for p in params:
                p_ref = self.__collect_param(p, reuse=reuse)
                params_out.append(p_ref)
        return params_out

    def get_params(self) -> dict[str, OpenApiParameter]:
        return dict(zip(self.__names, self.__params))


class OpenApiModelCollector:
    REF_TEMPLATE: Final[str] = "#/components/schemas/{model}"

    def __init__(self) -> None:
        self.__models: set[type[BaseModel]] = set()

    def get_schemas(self, suppress_title: bool = False) -> dict[str, JsonSchema]:
        """
        Generate a temporary model that has one parameter with each given model,
        pydantic will then generate the schemas for all parameters into $def and taking care of duplication etc.
        """
        model_name = "SchemaContainerForJsonSchemaGeneration"
        if model_name in [m.__name__ for m in self.__models]:
            raise FalconSwoopDocGenerationError(f"At least one schema uses a reserved name: {model_name}")
        model_params = {f"param{i}": (m, ...) for i, m in enumerate(self.__models)}
        model = create_model(model_name, **model_params)  # type: ignore
        model_schema = model_json_schema(
            model,
            by_alias=True,
            ref_template=self.REF_TEMPLATE,
            suppress_title=suppress_title,
        )
        schemas: dict[str, JsonSchema] = model_schema.get("$defs", {})
        return schemas

    def get_reference(self, model_type: type[BaseModel]) -> OpenApiReference:
        ref_url = self.REF_TEMPLATE.format(model=model_type.__name__)
        self.__models.add(model_type)
        return OpenApiReference(ref=ref_url)


class OpenApiGenerator:

    def __init__(
        self,
        resources: Sequence[ApiBaseResource],
        title: str,
        version: str,
        summary: str | None = None,
        description: str | None = None,
        settings: OpenApiGeneratorSettings | None = None,
    ) -> None:
        self.resources = resources
        self.settings = settings or OpenApiGeneratorSettings()
        self.__model_collector = OpenApiModelCollector()
        self.__param_collector = OpenApiParameterCollector()
        self.info = OpenApiInfo(
            title=title,
            version=version,
            summary=summary,
            description=description,
        )

    def __reset(self) -> None:
        self.__model_collector = OpenApiModelCollector()
        self.__param_collector = OpenApiParameterCollector()

    def map_schema(self, op_type: OpType) -> OpenApiReference | JsonSchema | None:
        if op_type is None:
            return None
        if issubclass(op_type, str):
            return {"type": "string"}
        if issubclass(op_type, (OpBinary, OpAsgiBinary)):
            return {"type": "string", "format": "binary"}
        return self.__model_collector.get_reference(op_type)

    def map_example(self, example: OpExample) -> OpenApiExample:
        value: dict[str, Any] | str
        if isinstance(example, BaseModel):
            value = example.model_dump(by_alias=True, mode="json")
        else:
            value = example
        return OpenApiExample(value=value)

    def map_media_type(self, type_doc: OpTypeDoc) -> OpenApiMediaType:
        return OpenApiMediaType(
            schema_=self.map_schema(type_doc.model_type),
            examples={name: self.map_example(example) for name, example in type_doc.examples.items()},
        )

    def map_request_doc(self, rd: OpRequestDoc) -> OpenApiRequestBody | None:
        content = {}
        for mime, resp_type in rd.by_mime.items():
            content[mime] = self.map_media_type(resp_type)
        return OpenApiRequestBody(required=rd.required, content=content)

    def map_response_doc(self, rd: OpResponseDoc) -> OpenApiResponse:
        content = {}
        for mime, resp_type in rd.by_mime.items():
            content[mime] = self.map_media_type(resp_type)
        return OpenApiResponse(description=rd.description, content=content)

    def map_operation_info(self, op_info: OpInfo) -> OpenApiOperation:
        req_body: OpenApiRequestBody | None = None
        if op_info.request_doc is not None:
            req_body = self.map_request_doc(op_info.request_doc)

        responses = {}
        for status_code, rd in op_info.response_docs.items():
            responses[str(status_code)] = self.map_response_doc(rd)

        parameters = []
        if isinstance(op_info, OpInfoWithSpec):
            parameters.extend(
                self.__param_collector.build_params(
                    param_type=OpenApiParameterType.QUERY,
                    param_input=op_info.func_spec.query_input,
                    reuse=self.settings.reuse_parameters_if_possible,
                    suppress_title=self.settings.suppress_title_in_param_schemas,
                )
            )
            parameters.extend(
                self.__param_collector.build_params(
                    param_type=OpenApiParameterType.HEADER,
                    param_input=op_info.func_spec.header_input,
                    reuse=self.settings.reuse_parameters_if_possible,
                    suppress_title=self.settings.suppress_title_in_param_schemas,
                )
            )
            parameters.extend(
                self.__param_collector.build_params(
                    param_type=OpenApiParameterType.PATH,
                    param_input=op_info.func_spec.path_input,
                    reuse=self.settings.reuse_parameters_if_possible,
                    suppress_title=self.settings.suppress_title_in_param_schemas,
                )
            )

        return OpenApiOperation(
            operationId=op_info.operation_id,
            summary=op_info.summary,
            description=op_info.description,
            tags=op_info.tags,
            deprecated=op_info.deprecated,
            parameters=parameters,
            requestBody=req_body,
            responses=responses,
        )

    def map_api_resource(self, resource: ApiBaseResource) -> OpenApiPathItem:
        operations: dict[HttpMethod, OpenApiOperation] = {}
        for op_info in resource.api_ops():
            operations[op_info.method] = self.map_operation_info(op_info)

        return OpenApiPathItem(
            **{method.lower(): op for method, op in operations.items()},
        )

    def generate(self) -> OpenApiGeneratorResult:
        self.__reset()

        paths: dict[str, OpenApiPathItem] = {}
        for r in self.resources:
            paths[r.api_route.plain] = self.map_api_resource(r)

        # TODO: security_schemas
        components = OpenApiComponents(
            schemas=self.__model_collector.get_schemas(suppress_title=self.settings.suppress_title_in_object_schemas),
            parameters=self.__param_collector.get_params(),
        )

        spec = OpenApiDocument(
            info=self.info,
            paths=paths,
            components=components,
        )
        return OpenApiGeneratorResult(spec=spec)
